language: python

services:
  - docker

before_install:
  - cd examples && docker-compose up -d && cd ..
  - docker ps -a
  - pip install .

script:
  - python3 -m robot -d ./docs examples/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
