language: python

services:
  - docker

before_install:
  - cd examples && docker-compose up -d && cd ..
  - docker ps -a
  - pip install .
  - sleep 30
  - docker inspect --format "{{json .State.Health.Status }}" $(docker-compose -f examples/docker-compose.yml ps -q)

script:
  - python3 -m robot -d ./docs examples/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
